### PR TITLE
Sentence transformer stuff

### PR DESCRIPTION
**Pull request by HLasse**
Adds 4 things:
1. Script to embed our data with sentence-transformers (~2 hours to embed all our text data using `paraphrase-multilingual-MiniLM-L12-v2`). 384 dimensional embeddings take up ~22GB disk space.
2. Script to fine-tune sentence-transformer on our data using SimCSE. 
3. Small CLI for manual evaluation of the usefulness/content of the different text SFIs.
4. Chunked feature generation

This will add torch and sentence-transformers as dependencies (which I know you are not a fan of due to slowing down tests). Managed to install CUDA enabled torch on Overtaci with the line from [here](https://www.notion.so/New-Conda-environment-on-Overtaci-3b24966774564ac6bf242a5b840752fa) so that's solved. Any thoughts on this?

### CODE REVIEW

**Comment by MartinBernstorff** [comment]
@HLasse Would you still like a review of this? :-)

**Comment by HLasse** [comment]
> @HLasse Would you still like a review of this? :-)

No need, Jakob has been thoroughly through it :)

**Comment by MartinBernstorff** [comment]
Excellent! Ready for merge, then?

**Comment by HLasse** [comment]
@bokajgd - do you think this is ready to merge :)

**Pull request merged**
