### PR TITLE
fix: circular imports on Ovartaci

### PR DESCRIPTION
**Pull request by MartinBernstorff**
@KennethEnevoldsen I had issues when running the patient slice files on Ovartaci due to "Circular imports" in the `__init__` files. 

Specifically, running `psycop/common/feature_generation/sequences/prediction_time_collater.py` in debug mode gave me circular imports. This is likely due to how we handle environments in Ovartaci, but I think not having nice imports is a cheaper price to pay than having the trace down this Ovartaci-specific problem. 

I've removed the `__init__` contents for now and updated the required imports, but super open to not removing them if you have a promising solution 👍

### CODE REVIEW

**Comment by MartinBernstorff** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Aarhus-Psychiatry-Research/psycop-common/714?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #710** <a href="https://app.graphite.dev/github/pr/Aarhus-Psychiatry-Research/psycop-common/710?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #708** <a href="https://app.graphite.dev/github/pr/Aarhus-Psychiatry-Research/psycop-common/708?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #705** <a href="https://app.graphite.dev/github/pr/Aarhus-Psychiatry-Research/psycop-common/705?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #714** <a href="https://app.graphite.dev/github/pr/Aarhus-Psychiatry-Research/psycop-common/714?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/Aarhus-Psychiatry-Research/psycop-common/714?utm_source=stack-comment).

**Review by KennethEnevoldsen — APPROVED** [review]
Overtaci specific errors is such a pain...

I think this change is fine (though I do appreciate nice looking imports), I think you are right in this case.

**Comment by MartinBernstorff** [comment]
> Overtaci specific errors is such a pain...
> 
> I think this change is fine (though I do appreciate nice looking imports), I think you are right in this case.

Agreed on both fronts. I'm nudging BI to hear if we can try out some work on their new KubeFlow-based platform to avoid these issues, but no news so far.

**Comment by MartinBernstorff** [comment]
### Merge activity

* **Jan 17, 10:22 AM**: [Graphite](https://app.graphite.dev/github/pr/Aarhus-Psychiatry-Research/psycop-common/714) rebased this pull request as part of a merge.

**Comment by KennethEnevoldsen** [comment]
It might also come with Kristoffer and Sørens collaboration on digital infrastructure for health (though that might take ages)

**Pull request merged**
