### PR TITLE
update restraint eval code

### PR DESCRIPTION
**Pull request by sarakolding**

### CODE REVIEW

**Comment by sarakolding** [comment]
@MartinBernstorff

**Comment by MartinBernstorff** [comment]
@sarakolding Feel free to merge this btw 👍

**Comment by sarakolding** [comment]
> @sarakolding Feel free to merge this btw 👍

thanks ;-)

**Comment by MartinBernstorff** [comment]
> > @sarakolding Feel free to merge this btw 👍
> 
> thanks ;-)

Haha, I thought you were waiting on me 😉

**Pull request merged**
